##
## KINOCHI REST API - SWAGGER 2 API
## https://swagger.io/docs/specification/2-0/basic-structure/
## https://editor.swagger.io/
##

swagger: '2.0'
info:
  title: Kinochi API
  version: "0.1"
  description: Kinochi API
host: api.kinochi.ru
basePath: /v1
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /films/:
    get:
      tags: [Films]
      operationId: kinochi.get_films
      summary: Return a list of films
      parameters:
        - in: query
          name: page
          description: Page number
          required: false
          type: integer
      responses:
        200:
          description: Return list of films
          schema:
            type: object
            properties:
              films:
                type: array
                items:
                  $ref: '#/definitions/Film'

parameters:
  uuid:
    name: uuid
    description: Film's Unique identifier
    in: path
    type: string
    required: true
    # pattern: "^[a-zA-Z0-9-]+$"

definitions:
  Film:
    type: object
    properties:
      id:
        type: string
        description: SELECT UUID()
        example: "7214905b-f8bf-11e8-af4b-000d3a208ac6"
        readOnly: true
      name_en:
        type: string
        description: Film name in English
        example: "Kinochi"
        minLength: 0
        maxLength: 100
      name_ru:
        type: string
        description: Film name in Russian
        example: "Киночи"
        minLength: 0
        maxLength: 100
      poster_url:
        type: string
        description: Poster url
        example: "http://kinochi.ru/poster.png"
        minLength: 0
        maxLength: 100
      rating_kinochi_positive:
        type: string
        description: Kinochi internal rating positive
        example: "1234"
        minLength: 1
        maxLength: 10
      rating_kinochi_negative:
        type: string
        description: Kinochi internal rating negative
        example: "123"
        minLength: 1
        maxLength: 10
      rating_imdb:
        type: string
        description: IMDB rating
        example: "7.2"
        minLength: 1
        maxLength: 5
      rating_kinopoisk:
        type: string
        description: Kinopoisk rating
        example: "8.3"
        minLength: 1
        maxLength: 5
      quality:
        type: string
        description: Film max quality
        example: "CamRip"
        minLength: 1
        maxLength: 15
      update_info:
        description: Update information
        example: "Вышла 8 серия 1 сезона"
        minLength: 1
        maxLength: 100
      details:
        type: object
        description: Extra data of films like images, description, series, etc
        properties:
          description:
            type: string
            example: "Это описание фильма"
          images:
            type: array
            example: ["http://kinochi.ru/1.jpg","http://kinochi.ru/2.jpg"]
            items:
              type: string
          series:
            type: array
            items:
              type: string
